Update MovieDetailsLinks.tsx
Radarr/Radarr pull request #10521
Opened 2024-10-07 03:50 UTC by dingdong42564

#### Database Migration
YES - XXXX | NO

#### Description
A few sentences describing the overall goals of the pull request's commits.

#### Screenshot (if UI related)

#### Todos
- [ ] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

2024-10-07 09:54 UTC, mynameisbogdan requested changes

2024-10-07 18:13 UTC, dingdong42564 commented
> Please change the base branch to develop, as you won't ever get this merged directly to master. :)

Sry, I'm kinda new to Github and I'm not sure how I change the base branch?

2024-10-07 18:17 UTC, mynameisbogdan requested changes

2024-10-17 05:38 UTC, masyk commented
Simkl Redirect API supports multiple parameters for search by multiple ids\title\year https://simkl.docs.apiary.io/#reference/redirect/redirect-to-simkl-trailer-or-twitter/redirect

2024-10-17 05:57 UTC, masyk commented
> `https://api.simkl.com/redirect?to=Simkl&type=movie&tmdb=348` seems to be the most suitable for us.

you can include multiple parameters in the url, it will find the one that is available.

2025-01-23 14:48 UTC, closed without merging