Adding the phrase "POL" to indicate the Polish language and the phrase "en" to indicate English. - Update LanguageParser.cs
Radarr/Radarr pull request #10546
Opened 2024-10-10 16:47 UTC by pcela

Adding the phrase "POL" to indicate the Polish language and the phrase "en" to indicate English.

#### Database Migration
NO

#### Description
Adding the phrase "POL" to indicate the Polish language and the phrase "en" to indicate English. This is intended to identify files marked with both "PL" and "POL" for Polish, as well as "en" and "eng" for English.

2024-10-10 17:19 UTC, bakerboy448 requested changes
- ci failed
- Need to add new tests for POL and additional test cases for EN for English

2024-10-10 17:31 UTC, mynameisbogdan requested changes
Please add test cases for your changes in `LanguageParserFixture`.

2024-10-10 19:56 UTC, pcela commented on src/NzbDrone.Core/Parser/LanguageParser.cs
> +                                                                                                          (?<polish>\b(?:(PL|POL)\b)|
I removed the redundant parenthesis “(”. Now it should be OK.

2024-11-27 21:02 UTC, bakerboy448 commented
Closing appears abandoned by OP and is no where near any state that would be merged. Requested changes never made.

Feel free to PR a working version at a future date

2024-11-27 21:02 UTC, closed without merging