Ignore "Percona Distribution" in Postgres version string
Radarr/Radarr pull request #10664
Opened 2024-11-14 13:13 UTC by aronsky

Drop the ` - Percona Distribution` suffix before passing the version string to `System.Version`.

#### Description
I tried using Sonarr with Percona Everest (a k8s operator that provisions various databases, including PostgreSQL). However, Percona Everest provisions a custom version of PostgreSQL, that reports its version as "16.3 - Percona Distribution". This causes an exception when that version is passed to the `System.Version` constructor.

2024-11-14 13:55 UTC, bakerboy448 commented
- this is a very hacky workaround
- needs tests
- likely should go upstream to sonarr first

2024-11-14 14:14 UTC, aronsky commented
* I agree, but don't have a better solution (unless you mean to remove everything that follows, e.g., a space or a dash, similar to the current regex that removes everything in parentheses). Of course, fixing it in Percona would be better, but I figured it'd be easier to do here
* This is a very straightforward replacement, not sure what to test for
* Sure. I've opened matching PRs in Sonarr and Prowlarr, too

2024-11-15 02:55 UTC, bakerboy448 requested changes
Concur with suggested concept change for Markus to parse out the version

https://github.com/Sonarr/Sonarr/pull/7385#issuecomment-2476490516

2024-11-21 00:40 UTC, RobinDadswell requested changes
As per Markus' comments on the Sonarr PR, I'd like to see this properly pull the version out, I would also like to see some a test with a few test cases as well just to make sure that it is working and continues to work if other changes are made in the future

2024-11-25 14:20 UTC, closed without merging