Add Albanian language.
Radarr/Radarr pull request #10663
Opened 2024-11-12 18:25 UTC by bpoxy

#### Database Migration
NO

#### Description
Hive (2021) is currently showing Original Language of English even though it is listed as Albanian on the The Movie Database.
This is because the Albanian language is not currently supported.

Added support for the Albanian language and also defaulted to Unknown language instead of English when a language is not found to avoid confusion, going forward.

#### Screenshot (if UI related)

#### Todos
- [x] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

*

2024-11-12 18:38 UTC, RobinDadswell requested changes
Can you add some tests, and also edit the commit message to be New: ...

2024-11-12 19:05 UTC, bpoxy commented
> Are we going to change the fallback original language in a minor version?
Do you want me to move that to separate PR?

> src/NzbDrone.Core/ImportLists/TMDb/TMDbLanguageCodes.cs needs updated too.
Thanks.

2024-11-12 19:16 UTC, bakerboy448 commented
> Are we going to change the fallback original language in a minor version?

This is a material breaking change that will prevent grabs from occurring and materially breaks/changes existing functionality. It should not be done as part of a minor release and should be held until v6 IMO.

2024-11-12 19:19 UTC, bpoxy commented
> > Are we going to change the fallback original language in a minor version?
> 
> This is a material breaking change that will prevent grabs from occurring and materially breaks/changes existing functionality. It should not be done as part of a minor release and should be held until v6 IMO.

Okay, I have removed the corresponding commit.

2024-11-22 17:05 UTC, bpoxy commented
Anyone know why these checks are failing?
![image](https://github.com/user-attachments/assets/98a04f64-c87b-4a85-9899-93da52227fdb)

2024-11-27 23:00 UTC, merged