Add keyboard shortcuts and delete redirect
Radarr/Radarr pull request #4964
Opened 2020-09-08 01:14 UTC by austinwbest

#### Database Migration
NO

#### Description
New: Add support for left/right arrows on the movie details to navigate through movies
New: Add support for ctrl+home and ctrl+end to jump to the top and bottom of the movie index
New: Add redirect to previous movie instead of index when deleting one

2020-09-08 04:11 UTC, Qstick commented on frontend/src/Movie/Details/MovieDetails.js
> +    if (event.keyCode === 37) {
Add to keyCodes and use `import * as keyCodes from 'Utilities/Constants/keyCodes';`

2020-09-13 02:12 UTC, Qstick commented
Should we add any of this to the keyboard shortcuts menu?

![image](https://user-images.githubusercontent.com/376117/93008656-0db90800-f545-11ea-8f91-dc52c5acfa90.png)

2020-09-13 03:25 UTC, austinwbest commented
I don't see the need to. Ctrl + home /end are standard top to bottom keys & nothing specific to radarr. Arrow keys are standard nav keys so.. Just my opinion anyways.

Your call.

2020-09-25 01:05 UTC, Qstick requested changes

2020-09-25 01:05 UTC, Qstick commented on frontend/src/Movie/Delete/DeleteMovieModalContent.js
> +      previousMovie: ''
not needed in state I don't think, you are only using the value from props and it's never changed in this component

2020-09-25 01:05 UTC, Qstick commented on frontend/src/Movie/Delete/DeleteMovieModalContentConnector.js
> +  onDeletePress = (deleteFiles, addImportExclusion, previousMovie) => {
You are essentially passing `previousMovie` from DeleteMovieModal, to this component then to `DeleteMovieModalContent` and back to here via this parameter... I think you can cut out ever handling it in `DeleteMovieModalContent` and just use the prop that is passed in from `DeleteMovieModal` here.... this avoids any change to `DeleteMovieModalConent` and avoids adding a parameter here.

2020-09-26 02:04 UTC, Qstick commented on frontend/src/Movie/Delete/DeleteMovieModalContentConnector.js
> -
Add this line back

2020-09-26 14:49 UTC, merged