New: Add icons for search results to indicate if it has been previous…
Radarr/Radarr pull request #5008
Opened 2020-09-12 18:58 UTC by austinwbest

#### Database Migration
NO

#### Description
New: Add icons for search results to indicate if it has been previously grabbed, failed or is in the blacklist.

#### Issues Fixed or Closed by this PR
Fixes #1619

2020-09-24 02:01 UTC, Qstick requested changes

2020-09-24 03:59 UTC, austinwbest commented on frontend/src/InteractiveSearch/InteractiveSearchRow.js
> +    for (const f in historyFailedDownloads) {
Moved to the connector & resolved the bigger one with finds instead. The second one utilizes includes and needs the object back.. It is a breaking for with minimal work so it should not be an impact.

2020-09-25 00:57 UTC, Qstick requested changes

2020-09-25 00:57 UTC, Qstick commented on frontend/src/InteractiveSearch/InteractiveSearchRowConnector.js
> +    for (const f in historyFailedDownloads) {
move these up to the connector instead of in the render

2020-09-25 00:57 UTC, Qstick commented on frontend/src/InteractiveSearch/InteractiveSearchRowConnector.js
> +      releaseGuid,
just use guid which is already there, no need to make a new one

2020-09-25 00:57 UTC, Qstick commented on frontend/src/InteractiveSearch/InteractiveSearchRowConnector.js
> +        releaseGuid={releaseGuid}
remove

2020-09-25 00:57 UTC, Qstick commented on frontend/src/InteractiveSearch/InteractiveSearchRowConnector.js
> +  releaseGuid: PropTypes.string,
remove

2020-09-25 11:16 UTC, Qstick requested changes

2020-09-25 11:16 UTC, Qstick commented on frontend/src/InteractiveSearch/InteractiveSearchRowConnector.js
> +        movieHistory,
Not used in SearchRow.js, not needed in return

2020-09-25 11:16 UTC, Qstick commented on frontend/src/InteractiveSearch/InteractiveSearchRowConnector.js
> +      movieHistory,
Remove

2020-09-25 11:16 UTC, Qstick commented on frontend/src/InteractiveSearch/InteractiveSearchRowConnector.js
> +        movieHistory={movieHistory}
Remove

2020-09-25 11:16 UTC, Qstick commented on frontend/src/InteractiveSearch/InteractiveSearchRowConnector.js
> +  releaseGuid: PropTypes.string,
Remove

2020-09-25 11:16 UTC, Qstick commented on frontend/src/InteractiveSearch/InteractiveSearchRowConnector.js
> +  movieHistory: PropTypes.array,
Remove

2020-09-25 11:16 UTC, Qstick commented on frontend/src/InteractiveSearch/InteractiveSearchRowConnector.js
> +  title: PropTypes.string
Remove

2020-09-25 14:56 UTC, merged