Adding Simkl integration
Radarr/Radarr pull request #5248
Opened 2020-10-22 06:32 UTC by Freaksed

#### Database Migration
YES | NO

#### Description
Beginning integration for simkl.com
First steps have been to duplicate trakt integrations and update references and api keys

#### Todos
- [ ] Tests
- [ ] Translation Keys

#### Issues Fixed or Closed by this PR

* #

2020-12-20 04:05 UTC, marine1988 commented
please accept

2020-12-20 05:29 UTC, austinwbest commented
> please accept

There is nothing to accept bud. It was noted as "started" 2 months ago but nothing since.

2021-01-09 16:28 UTC, AngelyChris commented
will this be implemented to v3? if so, im looking forward to this addition. cheers

2021-01-11 03:17 UTC, Qstick requested changes
This appears to be an exact copy of the trakt code, are we saying nothing is different? Also, I have no way to test this fully until we get auth hooked up. 

One note on the audio channels that needs fixed

2021-01-11 03:17 UTC, Qstick commented on src/NzbDrone.Core/Notifications/Simkl/SimklService.cs
> +            else if (audioChannels == "6.0" && audioFormat == "dts_ma")
Alot of this was fixed in the mediainfo implementation, you may want to sync back up with the trakt file

2021-01-11 03:17 UTC, Qstick commented on src/NzbDrone.Core/Notifications/Simkl/SimklProxy.cs
> +        private const string RenewUri = "https://auth.servarr.com/v1/simkl/renew";
@ta264 will need to add support for this.

2021-06-25 23:56 UTC, bakerboy448 commented
Closing; appears OP has abandoned; can reopen if needed

2021-06-25 23:56 UTC, closed without merging