Allow to set all logging levels in the settings
Radarr/Radarr pull request #5599
Opened 2020-12-22 14:06 UTC by hashworks

#### Database Migration
NO

#### Description
Currently, the frontend only allows to set 3 of the 6 available logging levels. This PR adds the missing ones.

#### Screenshot
![screenshot](https://fb.hash.works/zuLq0Bxg/)

#### Todos
- [X] Tests (is this tested at all?)
- [X] Translation Keys
- [ ] Wiki Updates (not really needed)

2020-12-22 14:08 UTC, bakerboy448 commented
If merged wiki updates are 100% needed.
Why would they not be?

https://wiki.servarr.com/Radarr_Settings#Logging

2020-12-22 14:11 UTC, bakerboy448 requested changes

2020-12-22 14:11 UTC, bakerboy448 commented on frontend/src/Settings/General/LoggingSettings.js
> +  { key: 'fatal', value: translate('Fatal') },
missing translate key
https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/Localization/Core/en.json

2020-12-22 14:14 UTC, hashworks commented on frontend/src/Settings/General/LoggingSettings.js
> +  { key: 'fatal', value: translate('Fatal') },
Added

2020-12-22 14:15 UTC, bakerboy448 approved these changes
code looks good; i'll defer to Q, Ta and Nit if this is something we want to do...

2020-12-22 14:22 UTC, hashworks commented
> If this will be merged wiki updates are 100% needed.

https://wiki.servarr.com/index.php?title=Settings_General&action=edit&section=18

```
=== Radarr ===
<section begin=radarr_settings_general_logging />
* Log level - Probably one of the most useful [[Radarr Troubleshooting|troubleshooting]] tools
** Fatal - This is the most basic way that Radarr gathers information and will only include hard fatal errors in the logs. 
*** This log file contains fatal entries.
** Error - Includes any errors that will require user attention.
*** This log file contains fatal and error entries.
** Warn - Besides errors this will also include warnings which might not need user attention.
*** This log file contains fatal, error and warn entries.
** Info - Shows all errors and warning plus very minimal amount of information in the logs. 
*** This log file contains fatal, error, warn and info entries.
** Debug - Debug will include all the information that Info includes plus more information that can be useful. 
*** This log files contains fatal, error, warn, info and debug entries
** Trace - The most advance and detailed logging on Radarr, Trace will include all the information gathered by Info and Debug and more. This is the most common type of log that is going to be asked for when troubleshooting on Discord or Reddit. If you're needing help please select your log to Trace and redo the task that was giving you problems to capture the log. 
*** This log files contains fatal, error, warn, info, debug and trace entries.
<section end=radarr_settings_general_logging />
```

2020-12-22 14:35 UTC, Qstick commented
@hashworks what is the goal with this one? I'd say info logs are sparse enough as it is. I think additional levels exposed to UI will just cause user confusion.

2020-12-22 14:53 UTC, hashworks commented
@Qstick A lot of the Info logs are of no relevance to me:

```
Dez 22 14:37:04 hostname Radarr[42]: [Info] RefreshMovieService: Skipping refresh of movie: Zoe
Dez 22 14:37:04 hostname Radarr[42]: [Info] DiskScanService: Scanning disk for Zoe
Dez 22 14:37:04 hostname Radarr[42]: [Info] DiskScanService: Completed scanning disk for Zoe
Dez 22 14:37:04 hostname Radarr[42]: [Info] ExistingMetadataImporter: Found 0 existing metadata files
Dez 22 14:37:04 hostname Radarr[42]: [Info] ExistingSubtitleImporter: Found 0 existing subtitle files
Dez 22 14:37:04 hostname Radarr[42]: [Info] ExistingOtherExtraImporter: Found 0 existing other extra files
Dez 22 14:37:04 hostname Radarr[42]: [Info] ExistingExtraFileService: Found 0 extra files
Dez 22 14:37:04 hostname Radarr[42]: [Info] RefreshMovieService: Skipping refresh of movie: Zombieland
Dez 22 14:37:04 hostname Radarr[42]: [Info] DiskScanService: Scanning disk for Zombieland
Dez 22 14:37:04 hostname Radarr[42]: [Info] DiskScanService: Completed scanning disk for Zombieland
Dez 22 14:37:04 hostname Radarr[42]: [Info] ExistingMetadataImporter: Found 0 existing metadata files
Dez 22 14:37:04 hostname Radarr[42]: [Info] ExistingSubtitleImporter: Found 0 existing subtitle files
Dez 22 14:37:04 hostname Radarr[42]: [Info] ExistingOtherExtraImporter: Found 0 existing other extra files
Dez 22 14:37:04 hostname Radarr[42]: [Info] ExistingExtraFileService: Found 0 extra files
Dez 22 14:37:04 hostname Radarr[42]: [Info] RefreshMovieService: Skipping refresh of movie: Zombieland: Double Tap
```

There is no need to inform me that `$randomMovie` was scanned (or skipped) without any change. All I want are warnings or errors on which I need to act.

I push all my journald Logs into an Elasticsearch instance which will alert me when the amount of logs goes over a specific threshold, for the Radarr Info logs I need to set it quite high.

2020-12-22 15:04 UTC, hashworks commented
The high amount of logs seem to happen when a full disc scan occurs:
![example](https://fb.hash.works/UZiZnPUf/)

From 14:30 to 14:40 there was a *small* amount of 12400 `[Info]` log entries without relevance to me.

2020-12-22 15:31 UTC, Qstick commented
You can set this manually in your config file for your instance, id prefer not to expose it to UI though... It'll be to much confusion for the average user having so many options... We already have issues with helping people thru changing logs to debug/trace because info doesn't give enough information.

2020-12-24 17:09 UTC, Qstick commented
Closing this and opening issue to make the “skipping refresh” messages debug instead of info which should help... also like mentioned you can likely set it to warn or error in your config file manually if wanted

2020-12-24 17:09 UTC, closed without merging