Added new PTP releasename
Radarr/Radarr pull request #5744
Opened 2021-01-14 12:38 UTC by quashtaki

#### Database Migration
NO

#### Description
This PR changes the PTP indexer so that the Releasename is more "consistent", much like how the AHD parser works. The reason for this is because PTP's releasenames tend to be pretty unorganized, especially older torrents, while the website itself is extremely organized. It uses the PTP API's "RemasterTitle" field which includes a lot of information about the movie such as HDR, Dolby Atmos, etc.

I also included a new toggle in the PTP Indexer settings, which turns the new ReleaseName on and off. It seems to be working with existing indexer settings.
#### Screenshot (if UI related)
[New](https://i.imgur.com/DVtvTOz.png) and [old](https://i.imgur.com/n19cN8x.png)
#### Todos
- [ ] Tests
- [ ] Translation Keys
- [ ] Wiki Updates

2021-01-16 14:14 UTC, TRaSH- commented
I'm against it it leaves out to much viable info and would break allot of custom formats people use.

![image](https://user-images.githubusercontent.com/6155095/104814125-7c68e380-580d-11eb-8f2f-fef197066c8c.png)

@rg9400

2021-01-16 14:29 UTC, ta264 commented
Thanks a lot for pointing that out @TRaSH- 

I agree that the new version needs fixing to include some of this extra info (especially the audio codec info) otherwise I don't think we can merge this.

2021-01-16 14:30 UTC, ta264 requested changes
As mentioned, in my opinion this needs to preserve the audio codec data at least.

2021-01-17 18:37 UTC, TRaSH- commented
i've talked with him about it in the channel,
his main reason for the changes is for the addition of the HDR tag recognizing.
being some groups don't add it to their release name, but with a new Custom Format it should pick those up after download.

2021-03-05 01:18 UTC, Qstick commented
Closing inactive

2021-03-05 01:18 UTC, closed without merging