Fixed: Updates to System > More Info
Radarr/Radarr pull request #5955
Opened 2021-02-21 17:14 UTC by bakerboy448

#### Database Migration
NO

#### Description
Frontend More Info updates to be consistent across Lidarr/Readarr/Radarr

#### Todos
-  Tests-N/A
- [X] Wiki Updates

#### Issues Fixed or Closed by this PR

*

2021-02-21 22:36 UTC, austinwbest requested changes

2021-02-21 22:36 UTC, austinwbest commented on frontend/src/System/Status/MoreInfo/MoreInfo.js
> +            <Link to="https://opencollective.com/radarr">Donate to Radarr</Link>
The title is translated, now that the link text is changed to not be an actual link it should be translated as well.

2021-02-21 22:36 UTC, austinwbest commented on frontend/src/System/Status/MoreInfo/MoreInfo.js
> +            <Link to="https://sonarr.tv/donate">Donate to Sonarr</Link>
The title is translated, link text should be translated as well.

2021-02-28 21:08 UTC, Qstick commented on frontend/src/System/Status/MoreInfo/MoreInfo.js
> +            <Link to="https://discord.gg/r5wJPt9">Radarr</Link>
Might as well change this while you are here

2021-03-04 04:44 UTC, Qstick commented
Make a section with icons for donations
![image](https://user-images.githubusercontent.com/376117/109912627-72def200-7c7a-11eb-88bb-b8ddf1fe3533.png)

2021-03-11 22:20 UTC, bakerboy448 commented
@Qstick punting on the icons; even with the bit of discussion the other day, still over my head.  seems like a good future idea tho, maybe FR it.

this has been rebased though

2021-03-12 03:13 UTC, austinwbest approved these changes

2021-03-12 14:03 UTC, RobinDadswell commented
@bakerboy448  want to sqaush these?

2021-03-12 14:03 UTC, Qstick approved these changes

2021-03-12 14:04 UTC, Qstick requested changes
Good call on the squash

2021-03-12 21:19 UTC, Qstick approved these changes

2021-03-12 21:19 UTC, merged