Pull Sonarr commit 'New: Allow user to choose whether delay profile should apply to release of the highest enabled quality'
Radarr/Radarr pull request #6218
Opened 2021-04-23 20:58 UTC by RobinDadswell

(cherry picked from commit d668e923af83ab7f1589d947fec9f40a3919e0b8)

* Fixes #5999

2021-05-02 21:49 UTC, bakerboy448 commented
Note: No wiki updates needed; exists already (common template w/ sonarr)

2021-05-04 19:10 UTC, RobinDadswell commented on src/NzbDrone.Core.Test/DecisionEngineTests/RssSync/DelaySpecificationFixture.cs
> +            Subject.IsSatisfiedBy(_remoteMovie, null).Accepted.Should().BeFalse();
This was my fix to the test failing - Taloth never got back to me but as the test was name "should be false" I assumed this should be false and not true as it is in the Sonarr Cherry-Pick :)

2021-05-08 13:41 UTC, Qstick requested changes
Just the two translates

2021-05-08 13:41 UTC, Qstick commented on frontend/src/Settings/Profiles/Delay/EditDelayProfileModalContent.js
> +                  <FormLabel>Bypass if Highest Quality</FormLabel>
Translate

2021-05-08 13:41 UTC, Qstick commented on frontend/src/Settings/Profiles/Delay/EditDelayProfileModalContent.js
> +                    helpText="Bypass delay when release has the highest enabled quality in the quality profile"
Translate

2021-05-08 23:32 UTC, Qstick approved these changes

2021-05-08 23:45 UTC, merged