fix up notification key misspelling
Radarr/Radarr pull request #6380
Opened 2021-06-07 19:52 UTC by bakerboy448

#### Database Migration
NO

#### Description

#### Screenshot (if UI related)

#### Todos
-  Tests
- [X] Translation Keys
- Wiki Updates

#### Issues Fixed or Closed by this PR

* Fixes #XXXX
found in Prowlarr; fixed in Prowlarr
https://github.com/Prowlarr/Prowlarr/pull/152

2021-06-07 19:55 UTC, RobinDadswell approved these changes

2021-06-07 19:56 UTC, RobinDadswell requested changes

2021-06-07 19:56 UTC, RobinDadswell commented on src/NzbDrone.Core/Localization/Core/en.json
> +}
Needs new line

2021-06-12 02:41 UTC, Qstick approved these changes

2021-06-12 02:41 UTC, merged