Enhancement: Split Chinese into Cantonese and Mandarin
Radarr/Radarr pull request #6522
Opened 2021-08-03 17:47 UTC by chryzsh

#### Database Migration
NO

#### Description
Added Cantonese and Mandarin as languages. Removed the mapping of these languages to Chinese.
Chinese still remains (and should remain) a separate language in Radarr, as a lot of releases only specify "Chinese", and not whether they are actually Cantonese or Mandarin.

#### Screenshot (if UI related)

#### Todos
- [ ] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #5970

2021-10-31 21:11 UTC, bakerboy448 commented
- conflicts
 - Lang 32 in use by https://github.com/Radarr/Radarr/pull/6385 
 - Lang 33 in use by https://github.com/Radarr/Radarr/pull/6415

use 34 and 35

2021-10-31 21:18 UTC, bakerboy448 requested changes
update language # & etc for conflicts

2022-01-26 16:47 UTC, bakerboy448 commented
conflicts

also bump lang to 35 and 38

2022-07-19 18:21 UTC, bakerboy448 commented
Closing; PR appears abandoned by OP

2022-07-19 18:21 UTC, closed without merging

2022-07-19 18:31 UTC, chryzsh commented
couldn't figure out what language # to put