New: Removing rtorrent downloads when seeding criteria have been met
Radarr/Radarr pull request #6735
Opened 2021-11-18 04:33 UTC by austinwbest

New: Removing rtorrent downloads when seeding criteria have been met

Fixes: #6320 
Fixes: #5219

2021-11-18 08:14 UTC, bakerboy448 commented
- [ ] (Update Wiki when fixed and merged)[https://wiki.servarr.com/radarr/settings#torrent-client-remove-download-compatibility]

2021-11-21 20:12 UTC, leaty commented
I can't speak for Radarr, but consider checking the other [changes](https://github.com/Sonarr/Sonarr/pull/3632/commits) that went into this by @Taloth, see if they're necessary here.

2021-11-23 20:07 UTC, Qstick requested changes

2021-11-23 20:07 UTC, Qstick commented on src/NzbDrone.Core/Download/Clients/rTorrent/RTorrent.cs
> +                    torrent.IsFinished &&
Change to `torrent.IsFinished && seedConfig != null &&` to fix tests, then good

2021-11-23 20:42 UTC, Qstick approved these changes

2021-11-23 21:06 UTC, merged