Jackett All healthcheck and verification
Radarr/Radarr pull request #6803
Opened 2021-12-09 12:55 UTC by RobinDadswell

#### Database Migration
NO

#### Description
Jackett all is bad - stopping adding/editing indexers that have this and calls a health check for those that have the all endpoint configured! 

#### Todos
- [ ] Tests
- [x] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)
- [ ] Verification for indexer settings

2021-12-13 19:37 UTC, bakerboy448 commented
- [ ] - healthcheck does not work

Existing Indexer 1
- URL `http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab`
- API `/api`

Existing Indexer 2
- URL `http://localhost:9117/torznab/all/api`
- API `/api`

- [X] - validation does work

New Indexer 3 ([as used by a user in sonarr](https://discord.com/channels/383686866005917708/383688189941907459/919984913330077696))
- URL `http://localhost:9117`
- API `/torznab/all/api`
![image](https://user-images.githubusercontent.com/55419169/145876717-484ecd5c-5110-46ae-9411-6a2545d88df7.png)


These should also all be added as tests

2021-12-15 01:28 UTC, bakerboy448 commented
No change from previous comment other than we now validate by API rather than host, which is a regression

healthcheck still does not trigger like it did before

![image](https://user-images.githubusercontent.com/55419169/146105982-1fcd6a5f-7c18-46a9-ae9a-fb163000f070.png)

2021-12-15 01:43 UTC, bakerboy448 commented
```
            var jacketAllProviders = _providerFactory.GetAvailableProviders().Where(
                i => i.Definition.ConfigContract.Equals("TorznabSettings"));

                // &&
                // ((i.Definition.Settings as TorznabSettings).BaseUrl.Contains("/torznab/all/api") ||
                // (i.Definition.Settings as TorznabSettings).BaseUrl.Contains("/api/v2.0/indexers/all/results/torznab") ||
                // (i.Definition.Settings as TorznabSettings).ApiPath.Contains("/torznab/all/api") ||
                // (i.Definition.Settings as TorznabSettings).ApiPath.Contains("/api/v2.0/indexers/all/results/torznab")));
```

jacketAllProviders  is empty

2021-12-15 09:00 UTC, RobinDadswell commented
> ```
> 
>             var jacketAllProviders = _providerFactory.GetAvailableProviders().Where(
> 
>                 i => i.Definition.ConfigContract.Equals("TorznabSettings"));
> 
> 
> 
>                 // &&
> 
>                 // ((i.Definition.Settings as TorznabSettings).BaseUrl.Contains("/torznab/all/api") ||
> 
>                 // (i.Definition.Settings as TorznabSettings).BaseUrl.Contains("/api/v2.0/indexers/all/results/torznab") ||
> 
>                 // (i.Definition.Settings as TorznabSettings).ApiPath.Contains("/torznab/all/api") ||
> 
>                 // (i.Definition.Settings as TorznabSettings).ApiPath.Contains("/api/v2.0/indexers/all/results/torznab")));
> 
> ```
> 
> 
> 
> jacketAllProviders  is empty

Yes it will be until it hits the foreach loop at which point it will run those lambda expressions

2021-12-15 12:36 UTC, bakerboy448 commented
I'm saying the healthcheck doesn't work and there is not a single provider found before it checks the other criteria based on commenting those out.  It finds no torznab settings indexers

2021-12-21 15:29 UTC, bakerboy448 commented
should add some tests otherwise works good

> Indexers using the unsupported Jackett 'all' endpoint: Jackett, Jackett2

- [X] healthcheck good
- [X] validation good

don't forget to [common] this if its not already and it'll need backporting for sonarr

2021-12-21 15:35 UTC, RobinDadswell commented
Already on the tests for the health check, validation tests yet to be looked at

2021-12-27 02:50 UTC, Qstick requested changes

2021-12-27 02:50 UTC, Qstick commented on frontend/src/System/Status/Health/Health.js
> +      return (
Can combine with above case as the link is identical

2021-12-27 02:50 UTC, Qstick commented on src/NzbDrone.Core/HealthCheck/Checks/IndexerJackettAllCheck.cs
> +                (i.Settings as TorznabSettings).ApiPath.Contains("/api/v2.0/indexers/all/results/torznab")));
Do all these need ToLowerInvariant() prior to compare?

2022-01-01 19:12 UTC, Qstick approved these changes

2022-01-01 19:26 UTC, merged