Fixed: Various Translations
Radarr/Radarr pull request #6809
Opened 2021-12-12 17:27 UTC by bakerboy448

#### Database Migration
NO

#### Description
A few sentences describing the overall goals of the pull request's commits.

#### Screenshot (if UI related)

#### Todos
- [ ] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

2021-12-12 19:06 UTC, Qstick commented on frontend/src/System/Status/Donations/Donations.js
> +        <div className={styles.logoContainer} title={translate('Radarr')}>
We don't actually want people to be able to change these via translation. Thus we haven't wrapped them.

2021-12-20 04:37 UTC, Qstick requested changes

2021-12-20 04:37 UTC, Qstick commented on frontend/src/Settings/Quality/Definition/QualityDefinitions.js
> +              {translate('SizeLimit')}
Not in en.json

2021-12-20 04:37 UTC, Qstick commented on frontend/src/Settings/DownloadClients/RemotePathMappings/RemotePathMappings.js
> +              {translate('LocalPath')}
Not in en.json

2021-12-20 04:37 UTC, Qstick commented on frontend/src/Settings/DownloadClients/RemotePathMappings/RemotePathMappings.js
> +              {translate('RemotePath')}
Not in en.json

2021-12-20 04:57 UTC, bakerboy448 commented
fixed up @austinwbest mental note: language script, need to review why it didnt add to en.json & why missing did not capture those

---

q - diffs for the latest force push
![image](https://user-images.githubusercontent.com/55419169/146713964-4f79efd1-9db2-4eaf-822d-3a335a1487e8.png)
![image](https://user-images.githubusercontent.com/55419169/146713983-7b486b19-18f4-48a1-86d4-a4bb15ec8184.png)
![image](https://user-images.githubusercontent.com/55419169/146713998-4520fd7b-6a3c-4c05-b564-887c53767af4.png)

2021-12-27 02:54 UTC, Qstick requested changes

2021-12-27 02:54 UTC, Qstick commented on frontend/src/InteractiveImport/Language/SelectLanguageModalContent.js
> +            {translate('SelectLanguage')}
SelectLanguages

2021-12-27 02:54 UTC, Qstick commented on frontend/src/Settings/ImportLists/ImportListExclusions/ImportListExclusions.js
> +              {translate('TMDBId')}
Don't translate

2021-12-27 03:14 UTC, Qstick approved these changes

2021-12-27 03:49 UTC, merged