Fixed: Healthchecks not firing due to missing IProvideHealthCheckWith…
Radarr/Radarr pull request #6948
Opened 2022-01-17 19:17 UTC by bakerboy448

…Message

#### Database Migration
NO

#### Description
title
per Ta it's in Readarr/Lidarr and not Radarr

#### Screenshot (if UI related)

#### Todos
- Tests
- Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

2022-01-17 23:58 UTC, Qstick commented
Isn't there an actual frontend health check that goes with this?

2022-01-18 00:00 UTC, bakerboy448 commented
> Isn't there an actual frontend health check that goes with this?

defer to @ta264 as he's who noticed it was missing from Radarr via https://github.com/Readarr/Readarr/pull/1328

2022-01-25 19:39 UTC, ta264 requested changes
I think you also need to edit the interface here: https://github.com/Radarr/Radarr/blob/093e076db06645106c5bc929b3b6d336308bd5dc/src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs#L25
To be
```IProvideHealthCheckWithMessage```

This should then hook up this function: https://github.com/Radarr/Radarr/blob/093e076db06645106c5bc929b3b6d336308bd5dc/src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs#L112

which right now is totally useless

2022-01-25 22:57 UTC, bakerboy448 commented
> I think you also need to edit the interface here:
> 
> https://github.com/Radarr/Radarr/blob/093e076db06645106c5bc929b3b6d336308bd5dc/src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs#L25
> 
> 
> To be
> `IProvideHealthCheckWithMessage`
> This should then hook up this function:
> 
> https://github.com/Radarr/Radarr/blob/093e076db06645106c5bc929b3b6d336308bd5dc/src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs#L112
> 
> which right now is totally useless

think i did that right / understood you right :)

2022-01-25 22:58 UTC, bakerboy448 commented on src/NzbDrone.Core/HealthCheck/HealthCheckService.cs
> +                    continue;
I think we can remove this as it's redundant?

2022-06-11 20:15 UTC, closed without merging