Add Catalan into language list
Radarr/Radarr pull request #7428
Opened 2022-07-19 18:10 UTC by dtalens

Add Catalan into language list

#### Database Migration
NO

#### Description
Add Catalan into language list. The translation using weblate is 100%. Translations update from Servarr Weblate #7415 

#### Todos
- [ ] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

2022-07-19 18:19 UTC, bakerboy448 commented
- Lang 36 is reserved for https://github.com/Radarr/Radarr/pull/6997
- Lang 37 is reserved for https://github.com/Radarr/Radarr/pull/6415
- Lang 35 and 38 are reserved for https://github.com/Radarr/Radarr/pull/6522

This would need to be Lang 39

2022-08-13 17:17 UTC, Qstick commented
@dtalens Is the intention here to support for UI translations, release parsing or both?

2022-08-24 15:07 UTC, dtalens commented
> @dtalens Is the intention here to support for UI translations, release parsing or both?

Both

2022-08-27 10:34 UTC, RobinDadswell requested changes
Please don't use merge commits - only ever rebase

2022-08-27 13:01 UTC, bakerboy448 requested changes
Also needs to be reset to drop the merge commit and rebased instead as robin noted

2022-08-27 13:01 UTC, bakerboy448 commented on src/NzbDrone.Core/Parser/LanguageParser.cs
> +                                                                            (?<catalan>\CA\b)",
`\C` doesn't make sense?
Why escape it?

2022-08-27 14:36 UTC, dtalens commented
> Also needs to be reset to drop the merge commit and rebased instead as robin noted

Please, how should I do rebase? Thanks.

2022-09-08 17:38 UTC, bakerboy448 commented
> 
> 
> 
> 
> 
> 
> > Also needs to be reset to drop the merge commit and rebased instead as robin noted
> 
> 
> 
> Please, how should I do rebase? Thanks.

https://stackoverflow.com/questions/17577409/git-remove-merge-commit-from-history


Or reset but leave the changes stages back on upstream develop and then recommit your changes

2022-09-08 20:29 UTC, closed without merging