Fixed: Tigole release group not being parsed and matched correctly, r…
Radarr/Radarr pull request #7448
Opened 2022-07-29 03:25 UTC by psylenced

#### Database Migration
NO

#### Description
 Release group `Tigole` not being matched correctly (due to using invalid naming) requiring manual imports.

This adds an exact exemption to allow it to be matched correctly.

#### Screenshot (if UI related)

#### Todos
- [ x ] Tests

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

2022-07-29 03:33 UTC, bakerboy448 commented
This was a release in the wild actually uploaded by Tigole and named improperly? 

What tracker / original release name out of curiosity?

2022-07-29 03:35 UTC, bakerboy448 requested changes

2022-07-29 03:35 UTC, bakerboy448 commented on src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
> +        [TestCase("Tigole.Should.Not.Use.Dots.2022.1080p.BluRay.x265.10bit.Tigole", "Tigole")]
```suggestion
        [TestCase("Movie.Should.Not.Use.Dots.2022.1080p.BluRay.x265.10bit.Tigole", "Tigole")]
```

2022-07-29 03:35 UTC, bakerboy448 commented on src/NzbDrone.Core/Parser/Parser.cs
> +        private static readonly Regex ExceptionReleaseGroupRegexExact = new Regex(@"(?<releasegroup>KRaLiMaRKo|E\.N\.D|D\-Z0N3|Koten_Gars|BluDragon|ZØNEHD|Tigole)", RegexOptions.IgnoreCase | RegexOpt
remove Tigole from ExceptionReleaseGroupRegex if it is added to ExceptionReleaseGroupRegexExact

2022-07-29 03:39 UTC, psylenced commented
This has occurred on about a dozen releases that I've noticed.

Few examples:

https://nzbindex.nl/?q=.tigole&max=25&minage=&maxage=&hidespam=1&hidepassword=0&sort=agedesc&minsize=&maxsize=&complete=0&hidecross=0&hasNFO=0&poster=

2022-07-29 03:46 UTC, bakerboy448 commented
Deleted the direct content link comment

examples

`"Eternals.2021.1080p.BluRay.x265.10bit.Tigole.zip.par2" - 9,76 GB - yEnc`
`"Ghostbusters.Afterlife.2021.1080p.BluRay.x265.10bit.Tigole.zip.nzb" yEnc`
`1607 - [00/93] - "Resident.Evil.Welcome.to.Raccoon.City.2021.1080p.BluRay.x265.10bit.Tigole.zip.nzb" yEnc`

from NZBIndex

These seem to be poorly renamed/retagged example that only exist on a single public indexer?

Some additional searching indicates basically all releases are `-Tigole` or `Tigole)` and only a small handful are poorly renamed.

@Qstick thoughts on the change for the support of small percentage of releases that are poorly renamed by uploaders?
maybe a dozen or so hits for `.Tigole` out of 580 results for `.Tigole` 
It's _probably_ fine. But the exact exception groups should be used sparingly.

2022-07-29 03:48 UTC, psylenced commented
I'll check logs and see if I can find a few more. Is there a way to have private comments?

Definitely agree it should be used sparingly, should be ok with `Tigole` not being an actual word. So shouldn't have false matches in titles.

2022-07-29 03:52 UTC, bakerboy448 commented
> I'll check logs and see if I can find a few more. Is there a way to have private comments?

no, but just release names are fine. the key is no links :)

2022-07-30 03:41 UTC, bakerboy448 approved these changes

2022-08-13 17:21 UTC, Qstick approved these changes

2022-08-13 17:21 UTC, merged