New: (UI) Indicate Custom Formats are Case Insensitive
Radarr/Radarr pull request #7487
Opened 2022-08-18 01:40 UTC by bakerboy448

#### Database Migration
NO

#### Description
A few sentences describing the overall goals of the pull request's commits.

#### Screenshot (if UI related)

#### Todos
- [ ] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

2022-08-19 01:11 UTC, Qstick requested changes

2022-08-19 01:11 UTC, Qstick commented on src/NzbDrone.Core/CustomFormats/Specifications/RegexSpecificationBase.cs
> +        [FieldDefinition(1, Label = "Regular Expression", HelpText = "Case Insensitive")]
Can we write this out a bit more, so it actually sounds like help text.

2022-08-19 01:12 UTC, bakerboy448 commented on src/NzbDrone.Core/CustomFormats/Specifications/RegexSpecificationBase.cs
> +        [FieldDefinition(1, Label = "Regular Expression", HelpText = "Case Insensitive")]
```suggestion
        [FieldDefinition(1, Label = "Regular Expression", HelpText = "Custom Format RegEx is Case Insensitive")]
```

2022-09-04 17:17 UTC, Qstick approved these changes

2022-09-04 17:17 UTC, merged