Hardcode IMAX uppercase for Edition Tags
Radarr/Radarr pull request #7566
Opened 2022-08-23 16:47 UTC by owine

#### Database Migration
 NO

#### Description
Hardcode IMAX Edition Tags to uppercase - ignore case preference.

#### Screenshot (if UI related)

#### Todos
- [ ] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

2022-08-23 17:51 UTC, bakerboy448 commented on src/NzbDrone.Core/Organizer/FileNameBuilder.cs
> +            {
What about `Extended Theatrical Version Imax`

2022-08-23 21:26 UTC, owine commented
Thanks @nuxencs for new logic

2022-08-27 17:30 UTC, bakerboy448 requested changes

2022-08-27 17:30 UTC, bakerboy448 commented on src/NzbDrone.Core/Organizer/FileNameBuilder.cs
> +                tokenHandlers["{Edition Tags}"] = m => CultureInfo.CurrentCulture.TextInfo.ToTitleCase(movieFile.Edition.ToLower().Replace("imax", "IMAX"));
This is applying IMAX and then converting it to title case

2022-08-27 17:30 UTC, bakerboy448 commented
- [ ] - also needs a test added

2022-09-09 01:39 UTC, Qstick commented
We should likely have an edition normalization method in the parser instead of just tacking on a replace in the filenamebuilder. Seems a bit hacky. 

Ideally, we'd normalize more than just IMAX

2022-10-02 17:59 UTC, closed without merging