Fixed: Add YTS.AG to the exception Release Groups
Radarr/Radarr pull request #7627
Opened 2022-09-23 21:37 UTC by dglava

#### Database Migration
 NO

#### Description
After troubleshooting in the Discord support channel, it was established that the alternate name for the YTS release group didn't get parsed correctly.
I have no experience with this and I hope I have added everything properly.

2022-09-23 21:55 UTC, bakerboy448 requested changes

2022-09-23 21:55 UTC, bakerboy448 commented on src/NzbDrone.Core.Test/ParserTests/LanguageParserFixture.cs
> +        [TestCase("Movie.Title.2022.1080p.BluRay.x264.-[YTS.AG]")]
drop, not needed

2022-09-24 02:43 UTC, Qstick requested changes

2022-09-24 02:43 UTC, Qstick commented on src/NzbDrone.Core/Parser/Parser.cs
> +        private static readonly Regex ExceptionReleaseGroupRegex = new Regex(@"(?<releasegroup>(Joy|YIFY|YTS.MX|YTS.LT|YTS.AG|FreetheFish|afm72|Anna|Bandi|Ghost|Kappa|MONOLITH|Qman|RZeroX|SAMPA|Silen
```suggestion
        private static readonly Regex ExceptionReleaseGroupRegex = new Regex(@"(?<releasegroup>(Joy|YIFY|YTS.(AG|LT|MX)|FreetheFish|afm72|Anna|Bandi|Ghost|Kappa|MONOLITH|Qman|RZeroX|SAMPA|Silence|theincognito|t3nzin|Vyndros|HDO|DusIctv|DHD|SEV|CtrlHD|-ZR-|ADC|XZVN|RH|Kametsu|r00t|HONE)(?=\]|\)))", RegexOptions.IgnoreCase | RegexOptions.Compiled);
```

Suggest simplifying this to eliminate some steps in regex calculation.

2022-09-24 18:27 UTC, merged