New: Make Emby imdb tags conditional
Radarr/Radarr pull request #8730
Opened 2023-06-22 20:49 UTC by bakerboy448

#### Database Migration
NO

#### Description
Emby does not support imdb- and uses imdb=
https://github.com/TRaSH-/Guides/pull/1386/files
https://github.com/TRaSH-/Guides/issues/1371
https://emby.media/community/index.php?/topic/118056-incorrect-identity-tv-shows/#comment-1245760

#### Screenshot (if UI related)

#### Todos
- Tests
- Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes N/A

2023-06-23 02:41 UTC, Qstick commented
You probably want to add a test that matches Emby documentation here

`[tmdbid=xxxx]` for tags

2023-06-23 03:09 UTC, Qstick requested changes

2023-06-23 03:09 UTC, Qstick commented on src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/IdFixture.cs
> +        public void should_skip_tmdbid_tag_if_null_with_equals()
This is impossible, no need to test, switch to IMDb with square brackets

2023-06-23 03:23 UTC, Qstick commented
Stick to handling IMDb null as was the intention of this PR, TMDb can never be null. The comment above was an example of their format direct from their docs.... Not a recommendation to add tmdbId.

2023-06-23 20:28 UTC, bakerboy448 commented
cleaned up accordingly.

need guidance on how to have the brackets be conditional.

`{Movie Title} {[imdb=ImdbId]}` did not work
`{Movie Title} [imdb={ImdbId}]` did not work
`{Movie Title} {[imdb={ImdbId}]}` did not work

2023-08-20 08:32 UTC, TRaSH- commented
Little bump for this PR, I would like to update the guide to follow the correct weird option Emby uses for their naming, but i can't merge it before this issue is resolved.

2023-09-27 12:30 UTC, darthShadow commented
Another option would be to ask Emby to support the Plex-style tags if someone wants to comment here: https://emby.media/community/index.php?/topic/121739-plex-format-id-tags-for-shows-movies/

2023-09-29 05:30 UTC, darthShadow commented
Following the above Feature Request, support for Plex-style tags has been added in the latest Emby beta (https://github.com/MediaBrowser/Emby.Releases/releases/tag/4.8.0.48):

```
Support more conventions with provider id values in folder names (moviedb, imdb, etc)
```

If someone can confirm it's working as expected, then this can be closed, I think.

2023-12-08 21:02 UTC, closed without merging