fix(parser): not correctly recognizing YIFY RlsGrp
Radarr/Radarr pull request #8883
Opened 2023-07-25 16:57 UTC by nuxencs

#### Database Migration
NO

#### Description
Fixing the release group parser not correctly recognizing `YIFY` in some releases.

#### Screenshot (if UI related)

#### Todos
- [x] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

2023-07-25 17:38 UTC, bakerboy448 requested changes

2023-07-25 17:38 UTC, bakerboy448 commented on src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
> +        [TestCase("Movie Title (2018) [BluRay] [1080p] [YTS] [YIFY]", "YIFY")]
Create a test with YIFY and yts flipped to ensure the existing exception logic is maintained

2023-07-25 18:26 UTC, nuxencs commented on src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
> +        [TestCase("Movie Title (2010) 1080p BrRip x264 - YIFY", "YIFY")]
aren't they in the correct one?
the HQMUX PR I did some time ago was exactly the same

2023-07-31 23:50 UTC, bakerboy448 commented on src/NzbDrone.Core.Test/ParserTests/ReleaseGroupParserFixture.cs
> +        [TestCase("Movie Title (2010) 1080p BrRip x264 - YIFY", "YIFY")]
Thought we had split the tests 😅

2023-07-31 23:50 UTC, bakerboy448 approved these changes

2023-08-19 02:13 UTC, merged