New: Default RSS Sync Interval to 15 minutes
Radarr/Radarr pull request #8947
Opened 2023-08-07 16:51 UTC by bakerboy448

#### Database Migration
NO

#### Description
- Default RSS to 15min from 60min for new installs
- Improve user experience
- aligns with upstream

#### Screenshot (if UI related)

#### Todos
- Tests
- Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
-  [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes missed RSS grabs for new users

2023-08-07 20:10 UTC, bakerboy448 commented
I'll look forward to the PR upstream increasing the time to more than 15 minutes then - https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Configuration/ConfigService.cs#L108

2023-08-08 14:06 UTC, bakerboy448 commented
suggestions for timing welcome....and should this go upstream? cc @markus101

2023-08-08 14:43 UTC, bakerboy448 commented
> Considering the frequency of new releases of movies vs episodes, I don't think they're the same.

The majority of the RSS feeds from sites are not filtered by category so the same quantity of releases needs to be processed and this point is moot.

Hell even 15 minutes is often frequently having gaps
![image](https://github.com/Radarr/Radarr/assets/55419169/d3fa3bdc-b946-4539-b252-6df45a53d875)

2023-08-08 15:18 UTC, markus101 commented
15 minutes is already the default is Sonarr, which for most sites is the minimum they allow.

Not being able to filter by category sounds like something indexers will need to address, I don't have these issues with the indexers I'm using.

2023-08-11 02:20 UTC, Qstick commented
Filtering by category for usenet indexers is in spec is it not? Maybe if you are using pirate bay through prowlarr or something similar I can see that popping up.

2023-08-18 04:00 UTC, Qstick requested changes
Fix the tests

2023-08-18 04:00 UTC, Qstick commented on src/NzbDrone.Core/Configuration/ConfigService.cs
> +            get { return GetValueInt("RssSyncInterval", 15); }
```suggestion
            get { return GetValueInt("RssSyncInterval", 30); }
```

2023-08-20 13:49 UTC, Qstick commented
Just a squash

2023-08-20 14:14 UTC, Qstick approved these changes

2023-08-20 14:14 UTC, merged