Add lowercasing ordinals (1st, 10th) and uppercase special words (IMAX, 3D, etc.) to edition tags
Radarr/Radarr pull request #9880
Opened 2024-03-28 22:00 UTC by brandonscript

#### Database Migration
NO

#### Description
Addresses #7649 
(Original goal was "Make IMAX Uppercase in Edition Tags", this now handles both lowercase (ordinals) and uppercase, as covered in the tests:

- 1st, 2nd, 3rd, 4th, 5th, 6th, 7th, 8th, 9th, 10th, ... 20th, ... 30th... etc.
- Imax → IMAX
- Hdr → HDR
- Sdr → SDR
- 3d → 3D

(And supports all case sensitivity options)

#### Screenshot (if UI related)

#### Todos
- [x] Tests
- [ ] ~Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)~
- [ ] [Wiki Updates](https://wiki.servarr.com) (Unsure if needed?)

#### Issues Fixed or Closed by this PR

* Fixes #7649

2024-04-06 14:17 UTC, bakerboy448 commented
tangent thought to this - any ideas for Extended vs Extended Cut and standardizing editions in general?

2024-04-06 15:05 UTC, brandonscript commented
@bakerboy448 I ended up doing this at one point: https://github.com/brandonscript/fylm/blob/main/fylm/fylmlib/parser.py#L310

(Would be a different ticket and PR, but I like it)

2024-06-25 20:12 UTC, brandonscript commented
Hey everyone, just checking in on this one to see if there's anything I should be doing to get this merged in, or if it's just a matter of waiting for someone's time to review?

2024-11-15 12:37 UTC, bakerboy448 requested changes
Just a couple changes
- use generic titles like Movie Title per the other parser tests
- use testcase names from actual file names just making the title generic as applicable

2024-11-15 12:39 UTC, bakerboy448 commented
And while there may be a better way to implement this I think getting something in at this point is better than nothing

2024-11-18 22:25 UTC, brandonscript commented
@bakerboy448 

- Made movie titles in test cases generic
- Not sure what you meant by "actual file names", esp. in contrast to the more generic "Movie Title" – can you elaborate?
- Fixed an issue where multiple words would get missed, and non-word-boundary separators would miss the match entirely – added test coverage for these edge cases.

2024-11-18 22:27 UTC, bakerboy448 commented
- rebase on upstream don't merge upstream; merge commits aren't allowed in develop

> Not sure what you meant by "actual file names", esp. in contrast to the more generic "Movie Title" – can you elaborate?

Look at all the other file name test cases they're based on production indexer/tracker or post-import file names rather than arbitrarily created random names

2024-11-18 22:32 UTC, brandonscript commented
> Look at all the other file name test cases

Er, yeah, sorry I looked at e.g. `ParserTests/AnimeVersionFixture.cs` and all the ones under `OrganizerTests/FileNameBuilderTests` – are you suggestion more like `ParsingServiceTests/GetMovieFixture.cs`? If not, if you can point me at a specific example that'd be great.

> rebase on upstream

Whoops, assumed (naively, so used to!) squash & merge, but I can revert and rebase.

2025-01-05 18:32 UTC, drtaru commented
Are we still just waiting on this? 
It's been a few months with no movement.

2025-01-22 17:52 UTC, bakerboy448 approved these changes, later dismissed
@mynameisbogdan  looks good to me.  do we merge this week or wait until develop cuts Sunday and merge after?

2025-01-22 19:52 UTC, brandonscript commented
> Actually looking at it now, I'm not that happy with the regex replacement. So not yet IMO.

Anything specific that's causing you to hesitate?

2025-01-22 20:18 UTC, brandonscript commented
> @mynameisbogdan You using the develop branch as source is a PITA for me. 😭

Oooh I can change it to a different source and re-implement what I've got so far, if that helps? Fwiw, I originally had it that way using replace, but it was only catching the first match ordinal, so splitting it seemed more sensible. But I for sure want to see this merged asap, so let me know what I can do to help!

2025-02-10 17:18 UTC, brandonscript commented
@mynameisbogdan anything else you need from me on this one? Would love to get it wrapped up :)

2025-05-31 11:46 UTC, merged

2025-05-31 12:35 UTC, denniseffing commented
Awesome, thank you all for your work! Looking forward to seeing this change live. 🎉